name: App CI CD
on:
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.22.1'

jobs:
  test:
    name: Run test and Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Set up Flutter
        run: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run test
        run: flutter test


