name: Build Android apk
on:
  workflow_call:
    inputs:
      flutter-version:
        required: true
        default: '3.27.3'
        type: string

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup-flutter/action.yaml
        with:
          flutter-version: ${{ inputs.flutter-version }}

      - name: Set up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
