name: Main Workflow
on:
  workflow_dispatch:

  pull_request:
    types: [ opened, closed ]
    branches: [ main, development, hotfix, release ]
    paths-ignore:
      - '**.md'

  push:
    branches:
      - main
      - development
      - hotfix
      - feature/**
    paths:
      - "lib/**"
      - 'android/**'
      - 'ios/**'
      - "pubspec.yaml"
      - ".github/workflows/**"


jobs:
  run-test:
    if: |
      (github.event_name == 'push' && github.ref != 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains('opened,synchronize', github.event.action))

    uses: ./.github/workflows/test_workflow.yaml
    with:
      flutter-version: '3.27.3'

  build-android:
    if: |
      (github.event_name == 'push' && contains('main development hotfix release', github.ref_name)) ||
      (github.event_name == 'pull_request' && contains('main development hotfix release', github.base_ref))

    needs: run-test
    uses: ./.github/workflows/build_android_workflow.yaml
    with:
      flutter-version: '3.27.3'

  build-ios:
    if: |
      (github.event_name == 'push' && contains('main development hotfix release', github.ref_name)) ||
      (github.event_name == 'pull_request' && contains('main development hotfix release', github.base_ref))

    needs: run-test
    uses: ./.github/workflows/build_ios_workflow.yaml
    with:
      flutter-version: '3.27.3'

  deploy-prod:
    needs: [ build-android, build-ios ]
    if: >
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'main'
    uses: ./.github/workflows/deploy.yaml


