name: Main Workflow
on:
  workflow_dispatch:

  pull_request:
    types: [ opened, synchronize ]
    branches: [ main, development, hotfix, release ]
    paths-ignore:
      - '**.md'

  push:
    branches:
      - main
      - development
      - hotfix
      - feature/**
    paths:
      - "lib/**"
      - 'android/**'
      - 'ios/**'
      - "pubspec.yaml"
      - ".github/workflows/**"


jobs:
  run-test:
    if: |
      (github.event_name == 'push' && contains('main development hotfix release', github.ref_name))

    uses: ./.github/workflows/test_workflow.yaml
    with:
      flutter-version: '3.27.3'

  build-android:
    if: |
      (github.event_name == 'push' && contains('main development hotfix release', github.ref_name))
    needs: run-test
    uses: ./.github/workflows/build_android.yaml
    with:
      flutter-version: '3.27.3'

  build-ios:
    if: |
      (github.event_name == 'push' && contains('main development hotfix release', github.ref_name))
    needs: run-test
    uses: ./.github/workflows/build_ios.yaml
    with:
      flutter-version: '3.27.3'

  deploy-prod:
    needs: [ build-android, build-ios ]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    uses: ./.github/workflows/deploy.yaml


