name: Test Job
on:
  workflow_call:
    inputs:
      flutter-version:
        required: true
        default: '3.27.3'
        type: string
env:
  FLUTTER_VERSION: ${{ inputs.flutter-version }}

jobs:
  test:
    name: Run test and Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true  # Caches Flutter SDK

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: ${{ runner.os }}-flutter

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run test
        run: flutter test
